data_faker/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from accounts.views import UserUpdateView, signup

urlpatterns = [
    path("admin/", admin.site.urls),
    path("accounts/", include("django.contrib.auth.urls")),
    path("accounts/<int:pk>/update", UserUpdateView.as_view(), name="profile-update"),
    path("accounts/signup/", signup, name="signup"),
    path("", include("schemas.urls", namespace="schemas")),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

schemas/urls.py
from django.urls import path
from .views import create_schema, SchemaList, SchemaDelete, SchemaDetail, download_file

urlpatterns = [
    path("schema/create/", create_schema, name="create_schema"),
    path("", SchemaList.as_view(), name="schema-list"),
    path("schema/<int:pk>/", SchemaDetail.as_view(), name="schema-detail"),
    path("schema/delete/<int:pk>/", SchemaDelete.as_view(), name="schema-delete"),
    path("dataset/<int:pk>/download/", download_file, name="download-file"),
]

app_name = "schemas"

accounts/models.py
from django.contrib.auth.models import AbstractUser


class User(AbstractUser):
    class Meta:
        ordering = ("username",)

schemas/models.py
from django.conf import settings
from django.core.validators import MinValueValidator
from django.db import models


class Schema(models.Model):
    COMMA = ","
    SEMICOLON = ";"
    TAB = "\t"

    DOUBLE_QUOTE = '"'
    SINGLE_QUOTE = '"'

    SEPARATOR_CHOICES = [
        (COMMA, "Comma(,)"),
        (SEMICOLON, "Semicolon(;)"),
        (TAB, "Tab(\t)"),
    ]

    STRING_CHARACTER_CHOICES = [
        (DOUBLE_QUOTE, 'Double Quotes(")'),
        (SINGLE_QUOTE, "Single Quotes(')"),
    ]

    title = models.CharField(max_length=255)
    user = models.ForeignKey(
        settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name="schemas"
    )
    column_separator = models.CharField(max_length=1, choices=SEPARATOR_CHOICES)
    string_character = models.CharField(max_length=1, choices=STRING_CHARACTER_CHOICES)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self) -> str:
        return self.title


class Column(models.Model):
    DATA_TYPE_CHOICES = [
        ("Integer", "Integer"),
        ("Full name", "Full name"),
        ("Job", "Job"),
        ("Phone number", "Phone number"),
        ("Company", "Company"),
        ("Text", "Text"),
        ("Date", "Date"),
        ("Address", "Address"),
    ]

    schema = models.ForeignKey(
        Schema,
        on_delete=models.CASCADE,
        related_name="columns",
    )
    name = models.CharField(max_length=64)
    data_type = models.CharField(max_length=64, choices=DATA_TYPE_CHOICES)
    min_value = models.IntegerField(null=True, blank=True)
    max_value = models.IntegerField(null=True, blank=True)
    order = models.IntegerField(validators=[MinValueValidator(0)])

    class Meta:
        unique_together = ("schema", "order")

    def __str__(self) -> str:
        return f"Schema id {self.schema} {self.name}"


class DataSet(models.Model):
    schema = models.ForeignKey(
        Schema, on_delete=models.CASCADE, related_name="datasets"
    )
    created_at = models.DateTimeField(auto_now=True)
    number_of_rows = models.IntegerField(validators=[MinValueValidator(1)])
    file = models.FileField(null=True, blank=True)
    is_ready = models.BooleanField(default=False)

    def __str__(self) -> str:
        return f"{self.schema} {self.created_at}"

accounts/forms.py
from django.contrib.auth.forms import UserCreationForm
from .models import User


class SignUpForm(UserCreationForm):
    class Meta:
        model = User
        fields = ["username", "email", "password1", "password2"]

schemas/forms.py
from django import forms
from .models import Schema, Column


class SchemaForm(forms.ModelForm):
    class Meta:
        model = Schema
        fields = ["title", "column_separator", "string_character"]


ColumnFormset = forms.modelformset_factory(
    Column,
    fields="__all__",
    extra=1,
    exclude=["schema"],
)

accounts/views.py
from django.contrib.auth import get_user_model
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import redirect, render
from django.urls import reverse_lazy
from django.views import generic

from accounts.forms import SignUpForm


class UserUpdateView(LoginRequiredMixin, generic.UpdateView):
    model = get_user_model()
    fields = ("username", "first_name", "last_name", "email")
    template_name = "schemas/user_form.html"
    success_url = reverse_lazy("schemas:schema-list")


def signup(request):
    if request.method == "POST":
        form = SignUpForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect("login")
    else:
        form = SignUpForm()
    return render(request, "registration/signup.html", {"form": form})

schemas/views.py
import os

from django.conf import settings
from django.contrib.auth import get_user_model
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import HttpResponseRedirect, HttpResponse
from django.shortcuts import render, redirect, get_object_or_404
from django.urls import reverse_lazy, reverse
from django.views import generic
from .forms import SchemaForm, ColumnFormset
from .models import Schema, Column, DataSet
from .task import create_fake_data


@login_required
def create_schema(request):
    schema_form = SchemaForm(request.GET or None)
    formset = ColumnFormset(queryset=Column.objects.none())
    if request.method == "POST":
        schema_form = SchemaForm(request.POST)
        formset = ColumnFormset(request.POST)
        if schema_form.is_valid() and formset.is_valid():
            schema = schema_form.save(commit=False)
            schema.user = get_user_model().objects.get(pk=request.user.pk)
            schema = schema_form.save()

            for form in formset:
                column = form.save(commit=False)
                column.schema = schema
                column.save()
            return redirect("schemas:schema-list")
    return render(
        request, "schemas/schema_create.html", {"form": schema_form, "formset": formset}
    )


class SchemaList(LoginRequiredMixin, generic.ListView):
    model = Schema
    paginate_by = 5
    queryset = Schema.objects.select_related("user")


class SchemaDetail(LoginRequiredMixin, generic.DetailView):
    model = Schema

    def get_queryset(self):
        queryset = super().get_queryset()
        return queryset.prefetch_related("datasets", "columns")

    def post(self, request, *args, **kwargs):
        schema_id = kwargs["pk"]
        schema = self.get_object()

        number_of_rows = request.POST.get("number_of_rows")

        if number_of_rows:
            dataset = schema.datasets.create(
                schema=schema_id, number_of_rows=number_of_rows
            )
            dataset.save()
            create_fake_data.delay(dataset.id, schema_id)

        return HttpResponseRedirect(
            reverse("schemas:schema-detail", kwargs={"pk": schema_id})
        )


class SchemaDelete(LoginRequiredMixin, generic.DeleteView):
    model = Schema
    success_url = reverse_lazy("schemas:schema-list")


@login_required
def download_file(request, pk):
    dataset = get_object_or_404(DataSet, pk=pk)
    file_path = dataset.file.url[1:]
    file_absolute_path = os.path.join(settings.MEDIA_ROOT, file_path)
    with open(file_absolute_path, "rb") as file:
        response = HttpResponse(file.read(), content_type="application/octet-stream")
        response[
            "Content-Disposition"
        ] = f'attachment; filename="{os.path.basename(file_absolute_path)}"'
        return response

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>{% block title %}Fake csv{% endblock %}</title>

  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/css/bootstrap.min.css"
        integrity="sha384-B0vP5xmATw1+K9KRQjQERJvTumQW0nPEzvF6L/Z6nronJ3oUOFUFpCjEUQouq2+l" crossorigin="anonymous">

  {% block stylesheets %}{% endblock %}
</head>
<body>

  <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <a class="navbar-brand" href="#">Fake CSV</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup"
            aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
      <div class="navbar-nav">
        <a class="nav-item nav-link active" href="{% url 'schemas:schema-list' %}">My schemas</a>
      </div>
      <div class="navbar-nav">
        <form action="{% url 'logout' %}" method="post">
        {% csrf_token %}
        <button type="submit" class="btn btn-secondary ml-2">Log out</button>
    </form>
      </div>
    </div>
  </nav>

  <div class="container">
    {% block content %}{% endblock %}
  </div>


  <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/js/bootstrap.bundle.min.js"
          integrity="sha384-Piv4xVNRyMGpqkS2by6br4gNJ7DXjqk09RmUpJ8jgGtD7zP9yug3goQfGII0yAns" crossorigin="anonymous"></script>
   {% block pagination %}
        {% include "includes/pagination.html" %}
      {% endblock %}
</body>
</html>

templates/includes/pagination.html
{% if is_paginated %}
  <ul class="pagination">
    {% if page_obj.has_previous %}
      <li class="page-item">
        <a href="?page= {{ page_obj.previous_page_number }}" class="page-link">prev</a>
      </li>
    {% endif %}
    <li class="page-item active">
      <span class="page-link">{{ page_obj.number }} of {{ paginator.num_pages }}</span>
    </li>
    {% if page_obj.has_next %}
      <li class="page-item">
        <a href="?page= {{ page_obj.next_page_number }}" class="page-link">next</a>
      </li>
    {% endif %}
  </ul>
{% endif %}

templates/schemas/schema_confirm_delete.html
{% extends 'base.html' %}

{% block content %}
<div class="min-vh-50 d-flex align-items-center">
    <div class="container border p-4 mx-auto bg-white col-md-4">
        <h1 class="text-center">Delete schema</h1>

        <p class="text-center">Are you sure you want to delete schema "{{ schema.name }}"?</p>

        <form action="{% url 'schemas:schema-delete' schema.pk %}" method="POST" class="mx-auto">
            {% csrf_token %}
            <div class="text-center">
                <button type="submit" class="btn btn-danger">Yes, delete</button>
                <a href="{% url 'schemas:schema-list' %}" class="btn btn-secondary">Cancel</a>
            </div>
        </form>
    </div>
</div>
{% endblock content %}

templates/schemas/schema_create.html
{% extends 'base.html' %}

{% load crispy_forms_tags %}

{% block content %}
   <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>

<div class="container">
    <div class="row mt-4">
    <h3>New Schema</h3>
        <form method="POST" action="" id="my-form">
            {% csrf_token %}
            {{ form|crispy }}

            <div id="form-container">
            <h3>Columns</h3>
                {{ formset.management_form }}
                {% for form in formset %}
                <div class="row schema-form mt-3">
                    {% crispy form %}
                    <button class="mt-4 btn btn-danger remove-form" type="button" style="height: 40px;">×</button>
                </div>
                {% endfor %}
            </div>

            <button id="add-form" class="btn btn-primary mt-2" type="button">Add Another column</button>
            <button id="create-button" class="btn btn-success float-right mt-2" type="submit">Create</button>
        </form>
    </div>
</div>


<script>
$(document).ready(function() {
    let addButton = $("#add-form");
    let totalForms = $("#id_form-TOTAL_FORMS");

    addButton.click(function(e) {
        e.preventDefault();

        let newForm = $(".schema-form:first").clone();
        let formRegex = RegExp("form-(\\d){1}-", "g");

        let formNum = $(".schema-form").length;
        newForm.find("input, select").each(function() {
            let oldName = $(this).attr("name");
            let newName = oldName.replace(formRegex, "form-" + formNum + "-");
            $(this).attr("name", newName);
            $(this).addClass("form-control col-md").val("");
        });

        let csrfToken = $("input[name='csrfmiddlewaretoken']").val();
        newForm.find("input[name='csrfmiddlewaretoken']").attr("id", "csrfmiddlewaretoken-" + formNum);
        newForm.find("input[name='csrfmiddlewaretoken']").val(csrfToken);

        $("#form-container").append(newForm);
        totalForms.val(formNum + 1);
    });

    $(document).on("click", ".remove-form", function(e) {
        e.preventDefault();
        if ($(".schema-form").length > 1) {
            $(this).closest(".schema-form").remove();
            let formNum = $(".schema-form").length;
            totalForms.val(formNum);
        } else {
            alert("You cannot remove the last form.");
        }
    });

    document.getElementById("create-button").addEventListener("click", function() {
        document.getElementById("my-form").submit();
    });
});
</script>
{% endblock content %}

templates/schemas/schema_detail.html
{% extends 'base.html' %}

{% block title %}Schema{% endblock %}

{% block content %}
  <div class="container">
    <h1>{{ schema.title }}</h1>
    <div class="table-responsive table-responsive-sm">
      <table class="table table-bordered table-sm">
        <thead>
            <tr>
                <th>Name</th>
                <th>Data Type</th>
            </tr>
        </thead>
        <tbody>
            {% for column in schema.columns.all %}
            <tr>
                <td>{{ column.name }}</td>
                <td>{{ column.data_type }}</td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
    </div></div>
<div class="container">
    <h2>Datasets</h2>
    <div class="row justify-content-end">
        <div class="col-md-6">
            <form action="#" method="post" class="form-inline justify-content-end">
                {% csrf_token %}
                <label for="number_of_rows" class="mr-4">Rows:</label>
                <input type="number" id="number_of_rows" name="number_of_rows" min="1" required class="form-control mr-2">
                <button type="submit" class="btn btn-primary">Generate</button>
            </form>
        </div>
    </div>
</div>
    <table class="table table-bordered">
    <thead>
        <tr>
          <th>#</th>
          <th>Created At</th>
          <th>Number of Rows</th>
          <th>Status</th>
          <th>Download</th>
        </tr>
    </thead>
    <tbody>
        {% for dataset in schema.datasets.all %}
        <tr>
            <td>{{ dataset.id }}</td>
            <td>{{ dataset.created_at }}</td>
            <td>{{ dataset.number_of_rows }}</td>
            <td>{% if dataset.is_ready %}
                <button class="btn btn-success" type="button" disabled>Ready</button>
            {% else %}
                <button class="btn btn-secondary" type="button" disabled>Processing</button>
            {% endif %}</td>
             <td>{% if dataset.is_ready == True %}
               <a href="{% url 'schemas:download-file' pk=dataset.id %}" class="btn btn-outline-warning">Download</a>
             {% endif %}</td>
        </tr>
        {% endfor %}
    </tbody>
</table>

{% endblock %}

templates/schemas/schema_list.html
{% extends 'base.html' %}

{% block content %}
  <div class="card">
    <div class="card-body">
      <h5 class="card-title">Personal Data</h5>
      <p class="card-text">Username: {{user.username}}</p>
      <p class="card-text">Email: {{user.email}}</p>
      <p class="card-text">Full name: {{user.first_name}} {{user.last_name}}</p>
      <div class="d-flex">
        <a href="{% url 'profile-update' pk=user.id%}" class="btn btn-primary">Edit Profile</a>
      </div>
    </div>
  </div>

<h1>Schema List <a href="{% url 'schemas:create_schema' %}">+</a></h1>
    <div class="container">
        <table class="table">
            <thead>
                <tr>
                    <th>#</th>
                    <th>Title</th>
                    <th>Modified</th>
                    <th>Actions</th>
                </tr>
            </thead>
            <tbody>
                {% for schema in schema_list %}
                  {% if user.id == schema.user_id %}
                    <tr>
                        <td>{{ schema.id }}</td>
                        <td><a href="{% url 'schemas:schema-detail' pk=schema.id %}">{{ schema.title }}</a></td>
                        <td>{{ schema.created_at }}</td>
                        <td>
                          <a class="btn btn-danger" href="{% url 'schemas:schema-delete' pk=schema.id %}">Delete</a>
                        </td>
                    </tr>
                  {% endif %}
                {% empty %}
                    <tr>
                        <td colspan="5">No schemas found.</td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
{% endblock content %}

templates/schemas/user_form.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% block content %}
  <div class="container border p-4 mx-auto bg-white col-md-6">
    <h1 class="text-center">Edit Profile</h1>

    <form method="post" action="" class="mx-auto">
      {% csrf_token %}

      {{ form|crispy }}

      <button type="submit" class="btn btn-primary mt-3">Save Changes</button>
    </form>
  </div>
{% endblock %}